### ISSUE TITLE
Serial interface usage issues

### ISSUE THREAD

**Issue by lemuellew** [newaetech/ChipSHOUTER#10]
I use the mobaxterm to connect to the usb interface, input no echo, and output garbled characters.
![image](https://user-images.githubusercontent.com/59448437/180201028-47f02f1e-19db-4aae-be2d-1797a3db3a8e.png)

**Comment by lemuellew** [comment]
I switched to picocom and had the same problem.

**Comment by lemuellew** [comment]
After 'implicit Cr in every lf' is enabled, the output becomes normal, but the input does not echo
![image](https://user-images.githubusercontent.com/59448437/180339747-2bf9317d-3f28-42f2-8792-b4d98d8a2dc5.png)

**Comment by colinoflynn** [comment]
iirc echo isn't enabled, we also assume local echo is enabled in the terminal emulator program. This is done partially as it makes scripting using the "raw" serial interface easier [i.e., if you don't want to use our Python interface], since you don't need to process your own echo'd back commands. Most terminal emulators support local echo option so it seemed to be the most useful compromise for customers, even though it's not perfect either way!

**Comment by lemuellew** [comment]
thanks
